### ISSUE TITLE
Set 6 ETA

### ISSUE THREAD

**Issue by plenaerts** [LorcanaJSON/LorcanaJSON#14]
Hi @Didero 

We at https://lorcanagrimoire.com are fully depending and waiting very anxiously for your work for set 6. We see you're working on it. Any hint on an ETA? 🙂 

Thx!!!

**Comment by Didero** [comment]
Always nice to see the LorcanaJSON data used!
I am indeed working on adding and verifying the cards from Set 6. It's taking a bit more work than expected. Ravensburger keep changing the design of Enchanted cards every set, which in this case required me to add a new way of parsing cards. I've also been a bit ill, slowing the work down. Plus, my dayjob also gets in the way.
I'm now aiming to have the English data for Set 6 ready on Thursday or Friday at the latest. The French data will probably be done a bit after the weekend.
Hopefully that's not too long a wait for you!

**Comment by huths0lo** [comment]
I have 100% of the data already.  I can whip up an endpoint in just a few minutes off api.33inkavenue.com:2053 if you tell me which data you need.

**Comment by Didero** [comment]
Thanks for the offer, but implementing a whole other API into this project would be more work than adapting my code for the Set 6 cards.

**Comment by huths0lo** [comment]
Gotcha.  Thought it was a one off scenario.

**Comment by Didero** [comment]
I ran into fewer problems and corrections than I feared, so I managed to already finish the data verification today. The update has just gone live. Enjoy!
