### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by Zarctus** [LorcanaJSON/LorcanaJSON#2]
Hey, thanks for sharing :)

I would like to know if it's possible to have the same thing for the french data language ?

`python main.py download --language fr`  doesn't work :'(

Thank you :)

**Comment by Didero** [comment]
Languages other than English aren't fully supported yet, which is one of the main things I want to improve, but that takes a lot of work.
Downloads should work for all languages though, I accidentally broke it when I added support for adding cards revealed in other places than the official app.
I pushed a fix for this issue, along with improving the 'download' action to also download a new JSON file if there is an updated version.
Let me know if it works for you now!

**Comment by Zarctus** [comment]
Magnifique !

It works now ! Thank you so much for your reactivity ^^
