### ISSUE TITLE
Ursula's Return

### ISSUE THREAD

**Issue by JSmurf** [LorcanaJSON/LorcanaJSON#7]
Hi! It's new set release week, which means I'm back here to ask about the new cards! 

It seems like most of the new cards are pretty straightforward, but I'm curious if you anticipate anything that might delay the update of your API to accommodate the new cards. I know that Ravensburger has stated that their app will not update until later this month, which I'm sure pushes back this API's update, since you're using the same API to source all the data. 

I'm also a bit curious how much you could do with just the images. 

I've noticed in the past that the file name for a given card number in a set is the same between sets, and using the `/images/[language]/expansions/[set number]/cards/[file size]/[file name]` "template," you can just swap out the set number or language to get different images. 

E.g. for card #141, the file name is `c9ca442765657fc90e9e779c34d0d2259d2c3c5b.jpg`, which for Set 1 is [Belle - Inventive Engineer](https://api.lorcana.ravensburger.com/images/en/expansions/1/cards/1468x2048/c9ca442765657fc90e9e779c34d0d2259d2c3c5b.jpg), for Set 2 is [Caterpillar - Calm and Collected](https://api.lorcana.ravensburger.com/images/en/expansions/2/cards/1468x2048/c9ca442765657fc90e9e779c34d0d2259d2c3c5b.jpg), and for Set 3 is [Genie - Cramped in the Lamp](https://api.lorcana.ravensburger.com/images/en/expansions/3/cards/1468x2048/c9ca442765657fc90e9e779c34d0d2259d2c3c5b.jpg). Therefore, by just swapping out the set number to 4, we can get the image for [Aurora - Tranquil Princess](https://api.lorcana.ravensburger.com/images/en/expansions/4/cards/1468x2048/c9ca442765657fc90e9e779c34d0d2259d2c3c5b.jpg). 

I have no idea how the file names are created, so the highest number I can find to refer to is 222 from Set 3 - [And Then Along Came Zeus Enchanted](https://api.lorcana.ravensburger.com/images/en/expansions/3/cards/1468x2048/1c6637a8f2e1f75e06ff9984894d6bd16a3a36a9.jpg), which in Set 4 is [The Wall Enchanted](https://api.lorcana.ravensburger.com/images/en/expansions/4/cards/1468x2048/1c6637a8f2e1f75e06ff9984894d6bd16a3a36a9.jpg). This gets us through the normal cards and the enchanted cards, but the previously revealed cards from the Illumineer's Quest (223-225) are unaccounted for. 

But if you could just use the data from set 3 to get the URLs for the Set 4 cards, you could at least pull all of the images and run your OCR on that, right?

**Comment by Didero** [comment]
It took quite a bit of work, but I just released an updated LorcanaJSON dataset with all the Set 4 cards, and some other minor fixes for older cards.
Thanks again for letting me know about the official card images being available even if the JSON wasn't!
